### ISSUE TITLE
cycleWindows does not have an assignable gesture

### ISSUE THREAD

**Issue by Simon818** [ogomez92/winWizard#6]
The windows+nvda+tab command for cycling between top-level windows is not assignable. Ideally, though it breaks NVDA gesture conventions, I'd like to set this back to nvda+tab. I can do this in code of course, but not everyone can, and it will revert with future updates. I also find that the gestures dialog is a good way for quickly finding keyboard commands associated with an add-on, so it's good to have all of the available gestures included.

**Comment by lukaszgo1** [comment]
@Simon818 wrote:
> The windows+nvda+tab command for cycling between top-level windows is not assignable.

That's not true - it can be reassigned it is just in a different category as noted in the readme.

> I also find that the gestures dialog is a good way for quickly finding keyboard commands associated with an add-on, so it's good to have all of the available gestures included.


I certainly agree with this. The only question which remains then is if it is okay to leave this script in the System focus category as it is now. For me this seems a logical choice - add-on specific scripts are in its own category and command which moves the system focus is separated though I'm certainly open to discuss this point further.

Since I believe your question is answered I'm going to close this issue though as I said above you can still comment on it if you want to make a case for moving this script into WinWizard's category in the input gestures dialog.

**Comment by Simon818** [comment]
Oh, that was a dumb oversight on my part. Apologies. I actually read this when I first downloaded the addon and then promptly forgot.

I can absolutely see why you did this, but it seems counterintuitive to have every gesture assignable in the WinWizard category except one. It does take away from the discoverability, and CycleWindows is an extremely useful command that I use daily across multiple apps, so I would vote to have it appear with the rest of the commands for the sake of consistency and so that other people can discover it more easily. I think that if other WinWizard commands appeared across preexisting NVDA categories, I would be more supportive of this one being in system focus. That's entirely up to you though, and I don't think your way is wrong.
